# Production environment docker-compose

services:
  frontend:
    build:
      context: ./shader-playground
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - embedding-service
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - embedding-data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  embedding-data:

networks:
  app-network:
    driver: bridge