# Production environment docker-compose
version: '3.8'

services:
  frontend:
    build:
      context: ./shader-playground
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - backend
      - embedding-service
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${BACKEND_URL:-https://backend.railway.app}
      - VITE_EMBEDDING_URL=${EMBEDDING_URL:-https://embedding.railway.app}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-https://frontend.railway.app}
      - EMBEDDING_SERVICE_URL=${EMBEDDING_URL:-https://embedding.railway.app}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M