[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[source]
repo = "lukashondrich/tinge"
branch = "main"
rootDirectory = "backend"
watchPatterns = ["backend/**"]

[variables]
NODE_ENV = "production"
PORT = "3000"
# Railway deployment trigger