[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
# Disable automatic detection
provider = "dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

# Disable automatic GitHub deployments - use GitHub Actions workflow instead
# [source]
# repo = "lukashondrich/tinge"
# branch = "main"
# rootDirectory = "backend"
# watchPatterns = ["backend/**"]

[variables]
NODE_ENV = "production"
PORT = "3000"
# Railway deployment trigger