[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
# Disable automatic detection
provider = "dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

# Remove GitHub integration entirely - use only GitHub Actions workflow
# No [source] section - Railway will not auto-deploy

[variables]
NODE_ENV = "production"
PORT = "3000"
# Railway deployment trigger