name: Clean Deploy Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      staging-url: ${{ steps.deploy-staging.outputs.url }}
      deployment-id: ${{ steps.deploy-staging.outputs.deployment-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: |
          echo "Installing Railway CLI..."
          npm install -g @railway/cli
          echo "Railway CLI installed successfully"
          railway --version || echo "Railway CLI version check failed"
          echo "Testing Railway authentication..."
          export RAILWAY_TOKEN=$RAILWAY_TOKEN
          railway whoami || echo "Railway authentication failed"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Frontend to Staging
        id: deploy-staging
        run: |
          echo "Starting frontend deployment..."
          cd shader-playground
          echo "Current directory: $(pwd)"
          ls -la | head -10
          echo "Checking for Dockerfile..."
          if [ -f "Dockerfile" ]; then
            echo "✅ Dockerfile found"
            cat Dockerfile | head -5
          else
            echo "❌ Dockerfile not found"
            exit 1
          fi
          echo "Starting Railway deployment..."
          echo "Creating Railway project configuration..."
          mkdir -p ~/.railway
          cat > ~/.railway/config.json << EOF
{
  "projectId": "7d38c550-e4c4-4cc0-83af-c1b705a990cb",
  "environmentId": "32d964ff-c497-4a04-b181-db754a3c7504",
  "serviceId": "fb761291-19e0-453a-8d2f-941eaba7fff6"
}
EOF
          echo "Railway config created, attempting deployment..."
          railway up --service frontend-staging --detach --verbose
          echo "Deployment command exit code: $?"
          echo "Frontend deployment completed"
          echo "url=https://frontend-staging-production-3876.up.railway.app" >> $GITHUB_OUTPUT
          echo "deployment-id=frontend-$(date +%s)" >> $GITHUB_OUTPUT
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Backend to Staging
        run: |
          echo "Starting backend deployment..."
          cd backend
          echo "Current directory: $(pwd)"
          ls -la | head -10
          echo "Starting Railway backend deployment..."
          echo "Creating Railway backend project configuration..."
          mkdir -p ~/.railway
          cat > ~/.railway/config.json << EOF
{
  "projectId": "c78dee4b-24f7-4750-b23a-998c620bf6eb",
  "environmentId": "32d964ff-c497-4a04-b181-db754a3c7504",
  "serviceId": "backend-staging-service-id"
}
EOF
          echo "Railway backend config created, attempting deployment..."
          railway up --service backend-staging --detach --verbose
          echo "Backend deployment completed"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  create-approval-issue:
    name: Create Production Approval Issue
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: always() && needs.deploy-staging.result == 'success'
    steps:
      - name: Create Production Approval Issue
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Creating production approval issue...')
            
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Production Deployment Approval Required - ' + context.sha.substring(0, 7),
              body: '## Production Deployment Request\n\n' +
                    '**Commit**: `' + context.sha + '`\n' +
                    '**Branch**: `' + context.ref + '`\n' +
                    '**Staging URL**: https://frontend-staging-production-3876.up.railway.app\n\n' +
                    '### Review Checklist\n' +
                    '- [ ] Staging environment tested and working\n' +
                    '- [ ] No breaking changes detected\n' +
                    '- [ ] Ready for production deployment\n\n' +
                    '### Approval Instructions\n' +
                    '**To approve**: Comment `approved` on this issue\n' +
                    '**To reject**: Comment `rejected` on this issue\n\n' +
                    '@lukashondrich',
              assignees: ['lukashondrich'],
              labels: ['deployment', 'production-approval']
            })
            
            console.log('Production approval issue created:', issue.number)

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'approved')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: |
          echo "Installing Railway CLI..."
          npm install -g @railway/cli
          railway --version
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Frontend to Production
        run: |
          echo "Starting production frontend deployment..."
          cd shader-playground
          echo "Creating Railway project configuration..."
          mkdir -p ~/.railway
          cat > ~/.railway/config.json << EOF
{
  "projectId": "7d38c550-e4c4-4cc0-83af-c1b705a990cb",
  "environmentId": "32d964ff-c497-4a04-b181-db754a3c7504",
  "serviceId": "tinge_frontend"
}
EOF
          echo "Deploying to production frontend..."
          railway up --service tinge_frontend --detach --verbose
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Backend to Production
        run: |
          echo "Starting production backend deployment..."
          cd backend
          echo "Creating Railway backend project configuration..."
          mkdir -p ~/.railway
          cat > ~/.railway/config.json << EOF
{
  "projectId": "c78dee4b-24f7-4750-b23a-998c620bf6eb",
  "environmentId": "32d964ff-c497-4a04-b181-db754a3c7504",
  "serviceId": "tinge_backend"
}
EOF
          echo "Deploying to production backend..."
          railway up --service tinge_backend --detach --verbose
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Close Approval Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## ✅ Production Deployment Completed!\n\n' +
                    '**Deployment Status**: Successful\n' +
                    '**Production Frontend**: https://tingefrontend-production.up.railway.app\n' +
                    '**Production Backend**: https://tingebackend-production.up.railway.app\n' +
                    '**Deployed at**: ' + new Date().toISOString() + '\n\n' +
                    'The production deployment has been completed and this issue is now closed.'
            })