name: Simple Deploy Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  test-deploy:
    name: Test Deploy Setup
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Test Railway CLI Installation
        run: |
          echo "Installing Railway CLI..."
          npm install -g @railway/cli
          echo "Railway CLI installed successfully"
          railway --version || echo "Railway CLI version check failed"
          echo "Checking Railway token..."
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "❌ RAILWAY_TOKEN is not set"
            exit 1
          else
            echo "✅ RAILWAY_TOKEN is set"
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Create Test Issue
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Creating test issue...')
            
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Test Issue - ${new Date().toISOString()}`,
              body: `This is a test issue to verify GitHub Actions workflow is working.`,
              labels: ['test']
            })
            
            console.log('Test issue created:', issue.number)