name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  deploy-staging:
    name: Deploy to Railway Staging
    runs-on: ubuntu-latest
    outputs:
      staging-url: ${{ steps.deploy-staging.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli
          railway --version
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Frontend to Staging
        id: deploy-staging
        run: |
          cd shader-playground
          mkdir -p ~/.railway
          cat > ~/.railway/config.json << 'EOF'
{
  "projectId": "7d38c550-e4c4-4cc0-83af-c1b705a990cb",
  "environmentId": "32d964ff-c497-4a04-b181-db754a3c7504",
  "serviceId": "fb761291-19e0-453a-8d2f-941eaba7fff6"
}
EOF
          railway up --service frontend-staging --detach --verbose
          echo "url=https://frontend-staging-production-3876.up.railway.app" >> $GITHUB_OUTPUT
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Backend to Staging
        run: |
          cd backend
          mkdir -p ~/.railway
          cat > ~/.railway/config.json << 'EOF'
{
  "projectId": "c78dee4b-24f7-4750-b23a-998c620bf6eb",
  "environmentId": "32d964ff-c497-4a04-b181-db754a3c7504",
  "serviceId": "backend-staging"
}
EOF
          railway up --service backend-staging --detach --verbose
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  create-approval-issue:
    name: Create Production Approval Issue
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: always() && needs.deploy-staging.result == 'success'
    steps:
      - name: Create Production Approval Issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Production Deployment Approval Required - ' + context.sha.substring(0, 7),
              body: '## Production Deployment Request\n\n' +
                    '**Commit**: `' + context.sha + '`\n' +
                    '**Staging URL**: https://frontend-staging-production-3876.up.railway.app\n\n' +
                    '### Review Checklist\n' +
                    '- [ ] Staging environment tested and working\n' +
                    '- [ ] No breaking changes detected\n' +
                    '- [ ] Ready for production deployment\n\n' +
                    '### Approval Instructions\n' +
                    '**To approve**: Comment `approved` on this issue\n\n' +
                    '@lukashondrich',
              assignees: ['lukashondrich'],
              labels: ['deployment', 'production-approval']
            })
            console.log('Production approval issue created:', issue.number)